name: Deploy Specific Game

on:
  workflow_dispatch:
    inputs:
      game_id:
        description: 'ID do jogo (ex: fx3YwKli0BtfsG2OBZwv)'
        required: true
      version:
        description: 'Versão do jogo (ex: 20250713153206)'
        required: true

jobs:
  deploy-game:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          pip install google-cloud-storage

      - name: Authenticate Firebase
        uses: w9jds/firebase-action@v2
        with:
          args: login:ci --token ${{ secrets.FIREBASE_TOKEN }}

      - name: Sync game assets from GCS
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_SERVICE_ACCOUNT_JSON }}
        run: |
          python ci/sync_games.py "${{ github.event.inputs.game_id }}" "${{ github.event.inputs.version }}"

      - name: Build frontend
        run: npm ci && npm run build

      - name: Deploy to Firebase Hosting
        run: firebase deploy --only hosting --token "$FIREBASE_TOKEN"
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
