name: Deploy Specific Game

on:
  workflow_dispatch:
    inputs:
      game_id:
        description: 'ID do jogo (ex: fx3YwKli0BtfsG2OBZwv)'
        required: true
      version:
        description: 'Versão do jogo (ex: 20250713153206)'
        required: true

jobs:
  deploy-game:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'       # if you use Workload Identity Federation instead

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_JSON }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: adapt2learn-api

      # 4) Baixa apenas o ZIP de deploy
      - name: Download deploy ZIP
        run: |
          mkdir -p public/games/${{ github.event.inputs.game_id }}
          gsutil cp \
            gs://adapt2learn-api.firebasestorage.app/games/${{ github.event.inputs.game_id }}/deploys/${{ github.event.inputs.version }}.zip \
            public/games/${{ github.event.inputs.game_id }}/deploy.zip

      # 5) Extrai o ZIP em public/games/{game_id}
      - name: Unzip deploy into public/games/
        run: |
          unzip -o public/games/${{ github.event.inputs.game_id }}/deploy.zip \
            -d public/games/${{ github.event.inputs.game_id }}
          rm public/games/${{ github.event.inputs.game_id }}/deploy.zip

      # 6) Setup Node.js para build local
      - name: Setup Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      # 7) Build do frontend (CRA copia tudo de public/ para build/)
      - name: Install & Build frontend
        env:
          CI: false
          NODE_OPTIONS: --openssl-legacy-provider
        run: |
          npm ci
          npm run build

      # 8) Deploy no Firebase Hosting com a Action oficial
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken:              ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.GCP_SERVICE_ACCOUNT_JSON }}
          channelId:              live
          projectId:              adapt2learn-api
