name: Deploy Specific Game

on:
  workflow_dispatch:
    inputs:
      game_id:
        description: 'ID do jogo'
        required: true
      version:
        description: 'Versão do jogo'
        required: true

jobs:
  deploy-game:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Python deps
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - run: |
          python -m pip install --upgrade pip
          pip install google-cloud-storage

      - name: Sync game assets from GCS
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_SERVICE_ACCOUNT_JSON }}
        run: |
          python ci/sync_games.py "${{ github.event.inputs.game_id }}" "${{ github.event.inputs.version }}"

      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      - name: Build frontend
        run: npm ci && npm run build

      - name: Deploy to Firebase Hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          firebase deploy --only hosting --non-interactive
